name: Publish Libraries
'on':
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repo ✅
        uses: actions/checkout@v2
        with:
          # We need to fetch all branches and commits so that Nx affected has a base to compare against.
          fetch-depth: 0
      - name: NRWL setup ✅
        uses: nrwl/nx-set-shas@v3

      - name: Install Dependencies 🔧
        run: |
          if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi
      - name: Pretty code 💄
        run: npx nx format:check
      - name: Lint ♻️
        run: npx nx affected -t lint --all --parallel=true
      - name: Build 📦
        run: npx nx affected -t build --all --parallel=true
      - name: Test 🧪
        run: npx nx affected -t test --all --ci --code-coverage --parallel=true
      - name: Release 🚀
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx nx run-many --target=deploy --parallel=false
